//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestBank.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class CustomerDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CustomerDetail()
        {
            this.CustomerAccounts = new HashSet<CustomerAccount>();
        }
    
        public int CustID { get; set; }
        [Required]
        [StringLength(10, MinimumLength = 5)]
        [Display(Name = "FirstName")]
        [RegularExpression(@"[A-Za-z]+", ErrorMessage = "Enter valid FirstName")]
        public string FirstName { get; set; }
        [Required]

        [Display(Name = "LastName")]
        [RegularExpression(@"[A-Za-z]+", ErrorMessage = "Enter valid LastName")]
        public string LastName { get; set; }
        [Required]
        public string Address1 { get; set; }
        [Required]
        public string Address2 { get; set; }
        [Required(ErrorMessage = "Please Enter mail")]
        [RegularExpression(@"^([\w\.\-]+)@([\w\-]+)((\.(\w){2,3})+)$", 
            ErrorMessage = "Enter a valid Email address")]
        public string EmailId { get; set; }
        [Required]
        public string MaritalStatus { get; set; }
        public Nullable<int> ZIPCode { get; set; }
        public Nullable<int> City { get; set; }
        public Nullable<int> State { get; set; }
        public Nullable<int> Country { get; set; }
        [Display(Name = "DOB")]
        [Required(ErrorMessage = "DOB is required.")]
        [DataValidation]
        public Nullable<System.DateTime> DOB { get; set; }
        [Required(ErrorMessage = "You must provide a phone number")]
        [Display(Name = "Phone")]
        [DataType(DataType.PhoneNumber)]
        [RegularExpression(@"^\(?([0-9]{3})\)?[-. ]?([0-9]{3})[-. ]?([0-9]{4})$", 
            ErrorMessage = "Not a valid phone number")]
        public Nullable<decimal> Mobile { get; set; }
    
        public virtual City City1 { get; set; }
        public virtual Country Country1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustomerAccount> CustomerAccounts { get; set; }
        public virtual PostalCode PostalCode { get; set; }
        public virtual State State1 { get; set; }
    }
}
